# Site Settings
name:         Jekyll Toolbox
description:  Jekyll Toolbox
keywords:     "Jekyll, Toolbox"


imgrepo: /assets/imgages
career-img: /assets/images/pic01.jpg

#
permalink: /:year-:month-:day/:title/

#
highlighter: pygments

#
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
  ]

#
url:		#
baseurl: 	#'/'

#
paginate: 10
paginate_path: ":num"

#
gems: 
  - jekyll-paginate

#
exclude:
  - work/**
