# Site Settings
name:         Jekyll Toolbox
description:  Jekyll Toolbox
keywords:     "Jekyll, Toolbox"


career-img: /assets/images/pic01.jpg

#
baseurl: #'/'

#
paginate: 10

exclude:
  - work/**
