title:              Clean Blog
email:              your-email@example.com
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            "/"
url:                "https://jekyll-toolbox.github.io"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
